sonar.projectKey=sarisjimenez3-design_aba-manager-system
sonar.organization=sarisjimenez3-design

sonar.projectName=Sistema de gestión ABA
sonar.projectVersion=1.0

sonar.sources=backend/src,mobile/src

sonar.exclusions=**/node_modules/**,**/dist/**,**/android/**,**/ios/**,**/.expo/**

sonar.sourceEncoding=UTF-8